name: AgileCoach
options:
  bundleIdPrefix: com.agilecoach
targets:
  AgileCoach:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: .
        excludes:
          - "project.yml"
          - ".github/**"
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        GENERATE_INFOPLIST_FILE: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_BITCODE: NO
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: "" # Empty for unsigned build
